function generateThought() {
    const thoughtElement = document.getElementById('thought');
    const buttonElement = document.getElementById('generateButton');

    // Add loading indicator
    buttonElement.innerHTML = '<div class="loading"></div>';

    // Simulate an API call or delay
    setTimeout(() => {
        const thoughts = [
            function generateThought() {
                const thoughtElement = document.getElementById('thought');
                const buttonElement = document.getElementById('generateButton');
            
                // Add loading indicator
                buttonElement.innerHTML = '<div class="loading"></div>';
            
                // Simulate an API call or delay
                setTimeout(() => {
                    const thoughts = [
    "The brain named itself.",
    "Your future self is probably thinking of you right now.",
    "The moment you’re born, you start to die.",
    "A different version of you exists in the minds of everyone who knows you.",
    "A group of squid should be called a squad.",
    "We laugh at dogs getting excited when they hear a bark on TV, but we also get excited when we hear a text notification.",
    "If you live to be 80, you’ve slept for about 26 years.",
    "We’ll never know what memories we had as children that we’ve forgotten.",
    "When you’re sick, the advice you’re given is to literally do nothing and wait to feel better.",
    "You’ve never actually seen your face, only reflections and pictures.",
    "When you clean something, you’re making something else dirty.",
    "If humans could fly, we’d probably consider it exercise and never do it.",
    "One day, someone will think of you for the last time in eternity.",
    "The word “swims” is still “swims” when turned upside down.",
    "If you say “my precious” in Gollum’s voice, nobody will question it.",
    "If you replace “W” with “T” in “What, Where, and When,” you get the answer.",
    "Someone out there vividly remembers something you said, which you’ve completely forgotten.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    "If you spell out every number, you won’t use a single “b” until you reach “billion.”",
    "An escalator can never break; it can only become stairs.",
    "Your age is just the number of laps you’ve done around a giant fireball in the sky.",
    "If you were to yell in space, it would be silent because sound needs a medium to travel.",
    "At some point, you were the youngest person on Earth.",
    "When you bite down on something, you’re actually biting up because you move your lower jaw.",
    "The oldest person on Earth was born with an entirely different set of humans.",
    "In a hundred years, Facebook will be filled with dead people.",
    "When you drink alcohol, you’re just borrowing happiness from tomorrow.",
    "Technically, when you turn 30, you’ve already lived more than 1 billion seconds.",
    "The only time the word incorrectly isn’t spelled incorrectly is when it’s spelled incorrectly.",
    "When you forget something, you are having a memory of not remembering.",
    "It’s impossible to imagine a new color.",
    "When you clench your fist, your brain tells your hand to punch itself.",
    "The key to happiness is low expectations.",
    "It’s weird to think that the word ‘abbreviation’ is such a long word.",
    "If two people on opposite sides of the world each drop a slice of bread, the Earth briefly becomes a sandwich.",
    "Nothing is on fire, fire is on things.",
    "The word ‘bed’ looks like a bed.",
    "The person who proofread Hitler’s speeches was a grammar Nazi.",
    "Every word you say is a new combination of sounds that will likely never be uttered in the same order ever again.",
    "The lighter was invented before the match.",
    "The plural of “I” is “we,” and the plural of “you” is also “you.”",
    "Saying “um” or “uh” is the brain’s equivalent of buffering.",
    "People say “bless you” when you sneeze because your heart stops for a millisecond.",
    "When you try to breathe through your nose, but you can’t, your brain immediately makes it a priority.",
    "The person you will marry is out there right now living their life, unaware that you will be their future.",
    "A hot dog is a sandwich.",
    "There’s a chance that in the future, archaeologists will dig up a Lego and think it was a religious artifact.",
    "You can’t stand backwards on stairs.",
    "A strawberry isn’t a berry, but a banana is.",
    "Your tongue knows exactly how everything you look at will feel.",
    "People with the fear of heights are more likely to survive falling off a cliff because they will scream for help.",
    "The sentence “I never said she stole my money” can have seven different meanings depending on which word you stress.",
    "A ‘jiffy’ is an actual unit of time.",
    "You will never be able to touch all your teeth with your tongue.",
    "The sun you see today is actually from 8 minutes ago.",
    "Your brain knows where all your organs are, but it won’t tell you.",
    "If everyone in the world sat together and held hands, someone would be sitting next to a murderer.",
    "Your shadow is proof that light has traveled nearly 93 million miles unobstructed, only to be stopped by you.",
    "The reason we fear clowns is because their painted faces hide their true emotions.",
    "A group of flamingos is called a flamboyance.",
    "Even if you have twins, there was a firstborn and a second born.",
    "Wearing a helmet increases your risk of getting hit by a car because drivers are less careful around you.",
    "Your hair doesn’t grow back darker after you shave; it just looks that way because it hasn’t been bleached by the sun yet.",
    "The ‘S’ in ‘Ulysses S. Grant’ doesn’t stand for anything.",
    "You never realize how much you’ve changed until you try to explain yourself to someone who doesn’t know you well.",
    "There is no word in the English language that rhymes with orange.",
    "The ‘D’ in D-Day stands for “Day.”",
    "No matter how fast you run, you’ll never be able to outrun your own farts.",
    "At this moment, you’re the oldest you’ve ever been and the youngest you’ll ever be again.",
    "One day, you will forget the last time you did something for the last time.",
    "You can’t hum while holding your nose.",
    "You share your birthday with millions of people, but none of them are exactly like you.",
    "In 100 years, there will be a whole new set of people living on Earth.",
    "A baby’s laugh is one of the most contagious things in the world.",
    "A pregnant woman can simultaneously be one of the oldest and youngest people in the room.",
    "When you close both eyes, you see darkness; when you close one eye, you see nothing.",
    "Water is the only thing that can be a solid, a liquid, and a gas at the same time.",
    "If you sneeze too hard, you can fracture a rib; if you try to suppress a sneeze, you can rupture a blood vessel.",
    "A million seconds is about 11 days; a billion seconds is about 31.7 years.",
    "The word ‘hello’ wasn’t used as a greeting until the invention of the telephone.",
    "No one can prove they aren’t in a simulation.",
    "Cemeteries would be a lot more interesting if the tombstones were interactive.",
    "Your skeleton is wet all the time.",
    "Technically, we are all older than the first human to ever exist.",
    "A mosquito’s purpose in life is to ruin yours.",
    "The tallest mountain on Earth is underwater.",
    "You can’t see your reflection in boiling water.",
    "If you drop soap on the floor, is the floor clean or the soap dirty?",
    "A ‘moment’ is 90 seconds.",
    "There are more stars in the universe than grains of sand on all the beaches on Earth.",
    "Every ‘C’ in ‘Pacific Ocean’ is pronounced differently.",
    "Lamps in video games use real electricity.",
    "When you ‘skydive,’ you’re actually ‘grounddiving.’",
    "If you eat a pound of food, you gain a pound of weight.",
    "The person who discovered milk was probably a little weird.",
    "The number of people older than you never increases.",
    "Everything in the universe is either pizza or not pizza.",
    "You can’t remember what your voice sounds like without a recording.",
    "The only difference between a salad and a compost pile is time.",
    "When you lose a sock, the washing machine eats it.",
    "When you’re born, you’re the youngest person alive.",
    "The Earth is smoother than a billiard ball if scaled down.",
    "Your brain thinks photos are people.",
    "At some point, your parents put you down and never picked you up again.",
    "People who are good at whistling are like magicians.",
    "There’s no such thing as an original thought.",
    "Every time you light a match, you’re just making the world a little bit darker.",
    "You’ve never heard the original version of your voice.",
    "When you kill a bug, you’re basically swatting at its descendants.",
    "The only part of your reflection you can lick is your tongue.",
    "You never realize you were wrong until you’re right.",
    "A ‘gut feeling’ is just your brain remembering something your conscious mind forgot.",
    "The letter ‘E’ is the most common letter in the English language.",
    "You could be walking past a murderer every day and not know it.",
    "When you die, the only part of you that dies is the part that knows you’re dead.",
    "We’re all just walking around on a giant rock spinning through space.",
    "A ‘new car smell’ is actually just the chemicals used in the manufacturing process.",
    "There’s a chance that you’ve walked past someone who will be your best friend.",
    "There are more life forms living on your skin than there are people on Earth.",
    "You’ve never seen your own face, only reflections and pictures.",
    "If you live in a country with daylight saving time, you’ve experienced a 23-hour day.",
    "Your skin is the largest organ in your body.",
    "Your hair and nails continue to grow after you die.",
    "The only reason your nose runs is because your brain is trying to protect your lungs.",
    "The average person will walk past 36 murderers in their lifetime.",
    "A ‘teaspoon’ is technically 4.92892 milliliters.",
    "A ‘second’ is 9,192,631,770 periods of radiation of a cesium-133 atom.",
    "The ‘b’ in ‘subtle’ is silent.",
    "The word ‘bookkeeper’ has three consecutive double letters.",
    "Your fingernails grow faster on your dominant hand.",
    "There’s a chance that someone out there loves you.",
    "A ‘rat king’ is a group of rats whose tails are tangled together.",
    "The word ‘queue’ is just the letter ‘Q’ followed by four silent letters.",
    "The sun is 400 times larger than the moon but is also 400 times farther away.",
    "There’s no such thing as a coincidence.",
    "The word ‘alphabet’ comes from the first two letters of the Greek alphabet: alpha and beta.",
    "A ‘baker’s dozen’ is 13, not 12.",
    "The only way to measure time is by the motion of objects.",
    "You can never experience the same moment twice.",
    "When you’re asleep, you’re the most vulnerable you’ll ever be.",
    "A ‘teapot’ is technically a type of kettle.",
    "The only difference between a horror movie and a comedy is the music.",
    "You’ve never seen yourself blink.",
    "Your sense of smell is linked to your memories.",
    "You’ve never seen the back of your own head.",
    "There’s no such thing as a perfect circle.",
    "A ‘chameleon’ can change its color but not its shape.",
    "There’s a chance that someone out there has the same thought as you at the exact same moment.",
    "You can never truly be alone.",
    "Your body is constantly repairing itself.",
    "The only thing you can’t get back is time.",
    "You’ve never seen your own brain.",
    "You’re always moving forward in time.",
    "You’re the only person who can see the world from your perspective.",
    "A ‘decade’ is just 10 years of moments strung together.",
    "There’s a chance that you’ve already met your soulmate.",
    "You can never truly know what someone else is thinking.",
    "You’re always one step closer to the end of your life.",
    "Your mind is the only thing you can’t escape from.",
    "A ‘mirror’ is just a piece of glass with a reflective coating.",
    "The only way to move forward is to take a step.",
    "You’re constantly shedding your skin.",
    "Your body is mostly water.",
    "The only thing separating you from the world is your skin.",
    "You’ve never seen your own brain.",
    "You’re the only person who can control your thoughts.",
    "A ‘memory’ is just a moment in time stored in your brain.",
    "You’re always moving forward in time.",
    "Your body is constantly changing.",
    "You’re the only person who can truly understand your thoughts.",
    "You’re the only person who can see the world from your perspective.",
    "A ‘moment’ is just a fleeting point in time.",
    "You’re constantly aging.",
    "Your mind is the only thing you can’t escape from.",
    "A ‘memory’ is just a moment in time stored in your brain.",
    "You’re always one step closer to the end of your life.",
    "You’re the only person who can truly understand your thoughts.",
    "Your body is mostly water.",
    "A ‘decade’ is just 10 years of moments strung together.",
    "Your sense of smell is linked to your memories.",
    "You’re constantly shedding your skin.",
    "A ‘chameleon’ can change its color but not its shape.",
    "You’re the only person who can control your thoughts.",
    "Your body is constantly repairing itself.",
    "You’re the only person who can see the world from your perspective.",
    "A ‘mirror’ is just a piece of glass with a reflective coating.",
    "You’re always moving forward in time.",
    "You can never experience the same moment twice.",
    "You can never truly be alone.",
    "A ‘teapot’ is technically a type of kettle.",
    "The only thing you can’t get back is time.",
    "You’re the only person who can truly understand your thoughts.",
    "A ‘memory’ is just a moment in time stored in your brain.",
    "You’re always one step closer to the end of your life.",
    "You’re constantly aging.",
    "Your mind is the only thing you can’t escape from.",
    "Your body is constantly changing.",
    "You’re the only person who can see the world from your perspective."
                    ];
            
                    const randomIndex = Math.floor(Math.random() * thoughts.length);
                    thoughtElement.innerHTML = thoughts[randomIndex];
            
                    // Restore button content
                    buttonElement.innerHTML = '<i class="fas fa-lightbulb"></i> Generate Thought';
                }, 2000); // Simulating a 2-second delay
            }
        ];

        const randomIndex = Math.floor(Math.random() * thoughts.length);
        thoughtElement.innerHTML = thoughts[randomIndex];

        // Restore button content
        buttonElement.innerHTML = '<i class="fas fa-lightbulb"></i> Generate Thought';
    }, 2000); // Simulating a 2-second delay
}